name: CONOCIENDOADIOS
favicon: null
layout_spectrum: 0.9729126698803157
typography_spectrum: 0.42203701520338655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.425078596919775
  lightness: 0.021594176068902016
  saturation: 0.40604565921239555
  rhythmicContrast: 0.8418147559277713
purpose: []
